# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Aetienne Sardon
tagline:          ''
description:      'Welcome to my personal website.'
url:              
baseurl:          /

author:
  name:           'Aetienne Sardon'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/asardon
